isomerpages/moe-methodistgirlssch

- _our-community/Primary Staff/Executive & Administrative Staff.md
- _secondary/Useful Links/Loan of MGS Uniform One.md
> Update file: Executive & Administrative Staff.md

- _parents/Primary Parents/Parent Volunteer (PV) Application.md
Hi Atiqa, something isn't right about your pull request. I can't see it on my page. I have amended this for Jasmine and created this for you to approve instead.
> Primary PV page

- _secondary-cca/Sports/Softball.md
- _secondary-cca/Sports/Squash.md
- _secondary-cca/Sports/Swimming.md
- _secondary-cca/Sports/Track.md
- _secondary-cca/Visual and Performing Arts/Drama Society.md
- _secondary-cca/Visual and Performing Arts/IDEAS.md
- _secondary-cca/Visual and Performing Arts/String Ensemble.md
Handbell: Lee Siang
Softball: Cassandra & Priscilla 
Chess: Lek Suan
Bowling: Deborah
Dance: Catherine Choo
Squash: Suat Bee
IDEAs: Lydia
Strings Ensemble: Arlene
Swimming: Elaine Chua
Indian Dance: Rebekkal
Drama: Anna
> Sec CCA pages

- _secondary-cca/Visual and Performing Arts/Indian Dance Club.md
- _secondary-cca/Visual and Performing Arts/International Dance.md
indian dance
international dance
> CCA updates

- _secondary-cca/Sports/Football.md
Dear Atiqa,
We need to include a para for football cca.. appreciate your help to review and approve.
Thank you.
> Included a new para for Football CCA

- _secondary/Useful Links/Loan of MGS Uniform One.md
Update information on Loan of Uniform 1 tp "Uniform One can only be picked up and returned on Mondays or Wednesdays between 2.30 and 3.30pm at the General Office, Level One."
> Update on Website Loan of Uniform 1

- _news-and-events/Open House/DSA Talent Areas.md
Hi Atiqa, I got a request from DSA coordinate to update the DSA page and remove the embedded video. Appreciate your review please :)
> update DSA page

- highlights/events/_posts/2024-04-16-link-MGS Open House 2024.md
- highlights/events/_posts/2024-04-16-link-MGS Open House.md
> Added 2024 behind MGS Open House

- highlights/events/_posts/2024-04-16-link-2024 Festival of the Arts.md
https://www.instagram.com/mgsfoa_kizuna/
> 2024 Festival of the Arts

- _admissions/Secondary Admission/Integrated Programme for Year 3.md
Hi sorry, there's an error.. can you please help to review again. Thanks
> Review please..

- _secondary-academic/1: 1 Learning Programme.md
> Changes to heading

- _secondary-academic/Aesthetics/Art.md
- _secondary-academic/Computer Studies.md
- _secondary-academic/Humanities/Global Studies and Global Perspectives and Inquiry.md
- _secondary-academic/Humanities/Humanities.md
- _secondary-academic/Integrated Programme/Integrated Programme.md
> Appreciate your help to review please.. a few additional changes..

- _secondary-cca/Visual and Performing Arts/String Ensemble.md
> added Arlene request... please review..

- _parents/Secondary Parents/Parent Teacher Meeting.md
- _parents/Secondary Parents/Parents' Briefing.md
- _secondary-cca/Visual and Performing Arts/Choir.md
- _secondary-cca/Visual and Performing Arts/Handbell Ensemble.md
> I have updated the Parent Engagement handout and added 2 video for FOA

- _our-community/Careers at MGS/Non Teaching Positions.md
> review please. Thank you

- _secondary-cca/Sports/Netball.md
> update netball page photo collage

- _news-and-events/Open House/Sharing Sessions.md
- _news-and-events/Open House/Student Voices.md
> updated videos in Open House page

- _news-and-events/Open House/Student Voices.md
> adjusted video size

- _secondary-cca/Visual and Performing Arts/Choir.md
- _secondary-cca/Visual and Performing Arts/Guitar Ensemble.md
- _secondary-cca/Visual and Performing Arts/Handbell Ensemble.md
- _secondary-cca/Visual and Performing Arts/String Ensemble.md
> change size of video on performing art pages

- _our-community/Secondary Staff/Key Personnel.md
- _our-community/Secondary Staff/Teachers.md
> change YH back to Sally

- _admissions/Secondary Admission/Integrated Programme for Year 3.md
- _secondary-cca/Visual and Performing Arts/Drama Society.md
- _secondary-cca/Visual and Performing Arts/Indian Dance Club.md
- _secondary-cca/Visual and Performing Arts/International Dance.md
> uploaded  FOA 2 video and updated IPY3 link

- _our-community/Secondary Staff/Executive & Administrative Staff.md
> update HR personnel

- _admissions/Awards and Scholarships/MGS Special Awards and Scholarships.md
> added values

- _our-community/Secondary Staff/Executive & Administrative Staff.md
- highlights/events/_posts/2024-04-22-link-Application for Admission into the 2025 Year 3 Integrated Programme.md
- highlights/events/_posts/2024-05-17-link-Application for Admission into the 2025 Year 3 Integrated Programme.md
> update y3 dates & Finance Manager

- _secondary-cca/Visual and Performing Arts/Guitar Ensemble.md
> syf update

- _secondary-cca/Achievements.md
> cca achievement

- _parents/Secondary Parents/Parent Teacher Meeting.md
> change in PTM note

- _our-community/Secondary Staff/Executive & Administrative Staff.md
- _secondary-academic/Assessment Schedules.md
> update exam schedule

- _our-community/Secondary Staff/Executive & Administrative Staff.md
> change HR name

- _news-and-events/MGS School Tour.md
- _news-and-events/collection.yml
- _our-community/Secondary Staff/Executive & Administrative Staff.md
> added sch tour & email address for FM

- _data/navigation.yml
> add in sub heading

- _data/navigation.yml
> amended url

- _admissions/Awards and Scholarships/MGS Special Awards and Scholarships.md
> scholarship write up

- _admissions/Secondary Admission/Direct School Admission for Secondary 1.md
- _our-community/Careers at MGS/Non Teaching Positions.md
- _our-community/Secondary Staff/Teachers.md
> amended staff list, DSA & HR

- _our-community/Secondary Staff/Key Personnel.md
> covering HOD PE

- _secondary-academic/Assessment Schedules.md
> Y4 EOY time table

- _admissions/Secondary Admission/Integrated Programme for Year 3.md
- _secondary-academic/Assessment Schedules.md
- highlights/mgstories/_posts/2023-11-16-link-MGeSprit 2023 Volume 2.md
> exam schedule

- _secondary-academic/Assessment Schedules.md
> updated naming

- _primary-cca/Commendation Award Ceremony.md
- _secondary-academic/Assessment Schedules.md
- _secondary-cca/Commendation Award Ceremony.md
> update exam schedule and CAC

- _secondary-academic/Assessment Schedules.md
> update of end of year examination timetable 2024 (Term 4) Year 3

- _news-and-events/Publications.md
update of MGS year book 2023 to high resolution
> update of MGS year book 2023 to high resolution

- _news-and-events/Publications.md
update MGS Yearbook 2023 to high resolution
> update MGS Yearbook 2023 to high resolution

- _parents/Secondary Parents/Booklist and Bookshop.md
> MGS Sec booklist 2025 update

- _admissions/Secondary Admission/Appeals for Admissions into Secondary 1.md
remove "a passport-size photo (max. 1MB), "
> Appeals for Admissions into Secondary 1 

- _secondary/Useful Links/For Students.md
change from pdf to formsg - https://go.gov.sg/reprint-of-documents
> useful link - students: request for reprint of documents
